name: 'Basic template github actions'
description: 'Um simples template de uma github action escrita em typescript'
inputs:
  organizationId: 
    description: 'Id da organização no Artia'
    require: true
  creatorEmail:
    description: 'Email do Bot cadastrado no Artia'
    required: true
  creatorPassword: 
    description: 'Senha do Bot cadastrado no Artia'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
