name: 'Basic template github actions'
description: 'Um simples template de uma github action escrita em typescript'
inputs:
  organizationId: #id da organização
    description: 'id da organização no Artia'
    require: true
  creatorEmail: #email cadastrado no artia com acesso ao projeto/atividade.
    description: 'email cadastrado no artia com acesso ao projeto e atividade'
    required: true
  creatorPassword: #senha para gerar token de acesso.
    description: 'senha utilizada para gerar token do artia'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
